# Generated by Django 5.2.4 on 2025-07-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_projectfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="files",
            field=models.ManyToManyField(
                related_name="projects", to="projects.projectfile"
            ),
        ),
    ]
